/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.AuctionsEntryAuctionIdGet200ResponsePayload

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param payload 
 */


data class AuctionsEntryAuctionIdGet200Response (

    @Json(name = "payload")
    val payload: AuctionsEntryAuctionIdGet200ResponsePayload? = null

)

