/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Element
import org.openapitools.client.models.KubrowAuction
import org.openapitools.client.models.LichAuction
import org.openapitools.client.models.RivenAuction
import org.openapitools.client.models.RivenAuctionAttributesInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type type of the item, in this case it's `kubrow`
 * @param attributes 
 * @param name 
 * @param masteryLevel Mastery level requirennment for that mod.
 * @param reRolls 
 * @param weaponUrlName url_name of any Kuva weapon
 * @param polarity 
 * @param modRank 
 * @param element 
 * @param damage 
 * @param ephemera Lich having Kuva ephemera (based on element)
 * @param quirk url_name of any Kuva quirk
 */


data class AuctionsCreatePostRequestItem (

    /* type of the item, in this case it's `kubrow` */
    @Json(name = "type")
    val type: kotlin.String? = null,

    @Json(name = "attributes")
    val attributes: kotlin.collections.List<RivenAuctionAttributesInner>? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    /* Mastery level requirennment for that mod. */
    @Json(name = "mastery_level")
    val masteryLevel: kotlin.Int? = null,

    @Json(name = "re_rolls")
    val reRolls: kotlin.Int? = null,

    /* url_name of any Kuva weapon */
    @Json(name = "weapon_url_name")
    val weaponUrlName: kotlin.String? = null,

    @Json(name = "polarity")
    val polarity: AuctionsCreatePostRequestItem.Polarity? = null,

    @Json(name = "mod_rank")
    val modRank: kotlin.Int? = null,

    @Json(name = "element")
    val element: Element? = null,

    @Json(name = "damage")
    val damage: kotlin.Int? = null,

    /* Lich having Kuva ephemera (based on element) */
    @Json(name = "ephemera")
    val ephemera: kotlin.Boolean? = false,

    /* url_name of any Kuva quirk */
    @Json(name = "quirk")
    val quirk: kotlin.String? = "undefined"

) {

    /**
     * 
     *
     * Values: madurai,vazarin,naramon,zenurik
     */
    @JsonClass(generateAdapter = false)
    enum class Polarity(val value: kotlin.String) {
        @Json(name = "madurai") madurai("madurai"),
        @Json(name = "vazarin") vazarin("vazarin"),
        @Json(name = "naramon") naramon("naramon"),
        @Json(name = "zenurik") zenurik("zenurik");
    }
}

