/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.AuctionsCreatePostRequestItem

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param startingPrice 
 * @param buyoutPrice If you want ∞ as buyout price, set this to `null`
 * @param item 
 * @param note 
 * @param minimalIncrement Minimum delta between the bids, Not appliable right now
 * @param minimalReputation Minimum reputation requirenment for participation in this auction.
 * @param `private` is this auction is private and only accesibly by direct link.
 */


data class AuctionsCreatePostRequest (

    @Json(name = "starting_price")
    val startingPrice: kotlin.Int,

    /* If you want ∞ as buyout price, set this to `null` */
    @Json(name = "buyout_price")
    val buyoutPrice: kotlin.Int?,

    @Json(name = "item")
    val item: AuctionsCreatePostRequestItem,

    @Json(name = "note")
    val note: kotlin.String? = null,

    /* Minimum delta between the bids, Not appliable right now */
    @Json(name = "minimal_increment")
    val minimalIncrement: kotlin.Int? = 1,

    /* Minimum reputation requirenment for participation in this auction. */
    @Json(name = "minimal_reputation")
    val minimalReputation: kotlin.Int? = 0,

    /* is this auction is private and only accesibly by direct link. */
    @Json(name = "private")
    val `private`: kotlin.Boolean? = false

)

