/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param email 
 * @param password 
 * @param authType 
 * @param deviceId Optional device_id, defined on client side.   This param help us to identify your device between login sessions. 
 */

data class AuthSigninPostRequest(

    @Json(name = "email")
    val email: String,

    @Json(name = "password")
    val password: String,

    @Json(name = "auth_type")
    val authType: AuthType? = AuthType.COOKIE,

    @Json(name = "device_id")
    val deviceId: String? = null

) {

    @JsonClass(generateAdapter = true)
    enum class AuthType(val value: String) {
        @Json(name = "cookie") COOKIE("cookie"),
        @Json(name = "header") HEADER("header")
    }
}

