/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param auction 
 * @param user 
 * @param `value` 
 * @param created 
 * @param updated 
 */


data class Bid (

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "auction")
    val auction: kotlin.String? = null,

    @Json(name = "user")
    val user: kotlin.String? = null,

    @Json(name = "value")
    val `value`: kotlin.Int? = null,

    @Json(name = "created")
    val created: java.time.OffsetDateTime? = null,

    @Json(name = "updated")
    val updated: java.time.OffsetDateTime? = null

)

