/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param patreonFounder 
 * @param subscription 
 * @param patreonBadge 
 */


data class CurrentUserPatreonProfile (

    @Json(name = "patreon_founder")
    val patreonFounder: kotlin.Boolean? = null,

    @Json(name = "subscription")
    val subscription: kotlin.Boolean? = null,

    @Json(name = "patreon_badge")
    val patreonBadge: CurrentUserPatreonProfile.PatreonBadge? = null

) {

    /**
     * 
     *
     * Values: bronze,gold,silver,platinum
     */
    @JsonClass(generateAdapter = false)
    enum class PatreonBadge(val value: kotlin.String) {
        @Json(name = "bronze") bronze("bronze"),
        @Json(name = "gold") gold("gold"),
        @Json(name = "silver") silver("silver"),
        @Json(name = "platinum") platinum("platinum");
    }
}

