/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param steamProfile 
 * @param patreonProfile 
 * @param xboxProfile 
 */


data class CurrentUserLinkedAccounts (

    @Json(name = "steam_profile")
    val steamProfile: kotlin.Boolean? = null,

    @Json(name = "patreon_profile")
    val patreonProfile: kotlin.Boolean? = null,

    @Json(name = "xbox_profile")
    val xboxProfile: kotlin.Boolean? = null

)

