/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.DropsourceMissionsInner
import org.openapitools.client.models.DropsourceNpcInner
import org.openapitools.client.models.DropsourceRelicsInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param missions 
 * @param relics 
 * @param npc 
 */


data class Dropsource (

    @Json(name = "missions")
    val missions: kotlin.collections.List<DropsourceMissionsInner>? = null,

    @Json(name = "relics")
    val relics: kotlin.collections.List<DropsourceRelicsInner>? = null,

    @Json(name = "npc")
    val npc: kotlin.collections.List<DropsourceNpcInner>? = null

)

