/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.DropsourceRelicsInnerRate

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param rarity How rare item is
 * @param rate 
 */


data class DropsourceRelicsInner (

    @Json(name = "id")
    val id: kotlin.String? = null,

    /* How rare item is */
    @Json(name = "rarity")
    val rarity: DropsourceRelicsInner.Rarity? = null,

    @Json(name = "rate")
    val rate: DropsourceRelicsInnerRate? = null

) {

    /**
     * How rare item is
     *
     * Values: common,uncommon,rare
     */
    @JsonClass(generateAdapter = false)
    enum class Rarity(val value: kotlin.String) {
        @Json(name = "common") common("common"),
        @Json(name = "uncommon") uncommon("uncommon"),
        @Json(name = "rare") rare("rare");
    }
}

