/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param intact 
 * @param exceptional 
 * @param flawless 
 * @param radiant 
 */


data class DropsourceRelicsInnerRate (

    @Json(name = "intact")
    val intact: java.math.BigDecimal? = null,

    @Json(name = "exceptional")
    val exceptional: java.math.BigDecimal? = null,

    @Json(name = "flawless")
    val flawless: java.math.BigDecimal? = null,

    @Json(name = "radiant")
    val radiant: java.math.BigDecimal? = null

)

