/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * item drop from enemy
 *
 * @param id 
 * @param rarity How rare item is
 * @param rate the droprate of the item being dropped from the enemy's drop list, the final droprate should be multipled with chance
 */


data class DropsourceNpcInner (

    @Json(name = "id")
    val id: kotlin.String? = null,

    /* How rare item is */
    @Json(name = "rarity")
    val rarity: DropsourceNpcInner.Rarity? = null,

    /* the droprate of the item being dropped from the enemy's drop list, the final droprate should be multipled with chance */
    @Json(name = "rate")
    val rate: java.math.BigDecimal? = null

) {

    /**
     * How rare item is
     *
     * Values: very_common,common,uncommon,rare,legendary
     */
    @JsonClass(generateAdapter = false)
    enum class Rarity(val value: kotlin.String) {
        @Json(name = "very_common") very_common("very_common"),
        @Json(name = "common") common("common"),
        @Json(name = "uncommon") uncommon("uncommon"),
        @Json(name = "rare") rare("rare"),
        @Json(name = "legendary") legendary("legendary");
    }
}

