/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * Values: impact,heat,cold,electricity,toxin,magnetic,radiation
 */

@JsonClass(generateAdapter = false)
enum class Element(val value: kotlin.String) {

    @Json(name = "impact")
    impact("impact"),

    @Json(name = "heat")
    heat("heat"),

    @Json(name = "cold")
    cold("cold"),

    @Json(name = "electricity")
    electricity("electricity"),

    @Json(name = "toxin")
    toxin("toxin"),

    @Json(name = "magnetic")
    magnetic("magnetic"),

    @Json(name = "radiation")
    radiation("radiation");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is Element) "$data" else null

        /**
         * Returns a valid [Element] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): Element? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

