/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ItemFull

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id Object id of requested item
 * @param itemsInSet 
 */


data class GetItemInfo200ResponsePayloadItem (

    /* Object id of requested item */
    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "items_in_set")
    val itemsInSet: kotlin.collections.List<ItemFull>? = null

)

