/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param urlName 
 * @param thumb Small icon
 * @param itemName depends on you `Language` header
 */


data class ItemShort (

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "url_name")
    val urlName: kotlin.String? = null,

    /* Small icon */
    @Json(name = "thumb")
    val thumb: kotlin.String? = null,

    /* depends on you `Language` header */
    @Json(name = "item_name")
    val itemName: kotlin.String? = null

)

