/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param urlName [a-z] snake case name of the item
 * @param icon it's a part of url, if you want to get an image you need to prepend assets root dirrectory: `http://warframe.market/static/assets/` 
 * @param iconFormat 
 * @param thumb Thumb of an icon
 * @param subIcon Usually, if item is part of set and not set itself, it will have `sub_icon`  like: **Mirage Blueprint** is part of **Mirage Set**, therefore the `icon` will be the **Mirage warframe** icon, and the `sub_icon` will be the **blueprint** icon 
 * @param modMaxRank in the next api version will be renamed to `max_rank`
 * @param subtypes relics and fishes are having this field
 * @param tags 
 * @param ducats 
 * @param quantityForSet 
 */


data class ItemCommon (

    @Json(name = "id")
    val id: kotlin.String? = null,

    /* [a-z] snake case name of the item */
    @Json(name = "url_name")
    val urlName: kotlin.String? = null,

    /* it's a part of url, if you want to get an image you need to prepend assets root dirrectory: `http://warframe.market/static/assets/`  */
    @Json(name = "icon")
    val icon: kotlin.String? = null,

    @Json(name = "icon_format")
    val iconFormat: ItemCommon.IconFormat? = null,

    /* Thumb of an icon */
    @Json(name = "thumb")
    val thumb: kotlin.String? = null,

    /* Usually, if item is part of set and not set itself, it will have `sub_icon`  like: **Mirage Blueprint** is part of **Mirage Set**, therefore the `icon` will be the **Mirage warframe** icon, and the `sub_icon` will be the **blueprint** icon  */
    @Json(name = "sub_icon")
    val subIcon: kotlin.String? = null,

    /* in the next api version will be renamed to `max_rank` */
    @Json(name = "mod_max_rank")
    val modMaxRank: kotlin.Int? = null,

    /* relics and fishes are having this field */
    @Json(name = "subtypes")
    val subtypes: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "tags")
    val tags: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "ducats")
    val ducats: kotlin.Int? = null,

    @Json(name = "quantity_for_set")
    val quantityForSet: kotlin.Int? = null

) {

    /**
     * 
     *
     * Values: land,port
     */
    @JsonClass(generateAdapter = false)
    enum class IconFormat(val value: kotlin.String) {
        @Json(name = "land") land("land"),
        @Json(name = "port") port("port");
    }
}

