/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ItemsUrlNameOrdersGet200ResponsePayloadOrdersInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param orders 
 */


data class ItemsUrlNameOrdersGet200ResponsePayload (

    @Json(name = "orders")
    val orders: kotlin.collections.List<ItemsUrlNameOrdersGet200ResponsePayloadOrdersInner>? = null

)

