/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.LangInItemDropInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param itemName 
 * @param description 
 * @param wikiLink 
 * @param drop 
 */


data class LangInItem (

    @Json(name = "item_name")
    val itemName: kotlin.String? = null,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "wiki_link")
    val wikiLink: kotlin.String? = null,

    @Json(name = "drop")
    val drop: kotlin.collections.List<LangInItemDropInner>? = null

)

