/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param name translated name of the location \\\\ item
 * @param link link to the internal or extarnal source with information about that location
 */


data class LangInItemDropInner (

    /* translated name of the location \\\\ item */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* link to the internal or extarnal source with information about that location */
    @Json(name = "link")
    val link: kotlin.String? = null

)

