/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Element

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type type of the item, in this case it's `lich`
 * @param weaponUrlName url_name of any Kuva weapon
 * @param element 
 * @param damage 
 * @param ephemera Lich having Kuva ephemera (based on element)
 * @param quirk url_name of any Kuva quirk
 * @param name Will not be used for now (?)
 */


data class LichAuction (

    /* type of the item, in this case it's `lich` */
    @Json(name = "type")
    val type: kotlin.String? = null,

    /* url_name of any Kuva weapon */
    @Json(name = "weapon_url_name")
    val weaponUrlName: kotlin.String? = null,

    @Json(name = "element")
    val element: Element? = null,

    @Json(name = "damage")
    val damage: kotlin.Int? = null,

    /* Lich having Kuva ephemera (based on element) */
    @Json(name = "ephemera")
    val ephemera: kotlin.Boolean? = false,

    /* url_name of any Kuva quirk */
    @Json(name = "quirk")
    val quirk: kotlin.String? = "undefined",

    /* Will not be used for now (?) */
    @Json(name = "name")
    val name: kotlin.String? = null

)

