/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * SolNodes basically
 *
 * @param id 
 * @param urlName 
 * @param icon 
 * @param thumb 
 * @param minLevel min lvl of npc on this location
 * @param maxLevel max lvl of npc on this location
 * @param faction 
 * @param nodeName Node name
 * @param systemName System name
 */


data class Location (

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "url_name")
    val urlName: kotlin.String? = null,

    @Json(name = "icon")
    val icon: kotlin.String? = null,

    @Json(name = "thumb")
    val thumb: kotlin.String? = null,

    /* min lvl of npc on this location */
    @Json(name = "min_level")
    val minLevel: java.math.BigDecimal? = null,

    /* max lvl of npc on this location */
    @Json(name = "max_level")
    val maxLevel: java.math.BigDecimal? = null,

    @Json(name = "faction")
    val faction: Location.Faction? = null,

    /* Node name */
    @Json(name = "node_name")
    val nodeName: kotlin.String? = null,

    /* System name */
    @Json(name = "system_name")
    val systemName: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: infested,grineer,corpus,corrupted
     */
    @JsonClass(generateAdapter = false)
    enum class Faction(val value: kotlin.String) {
        @Json(name = "infested") infested("infested"),
        @Json(name = "grineer") grineer("grineer"),
        @Json(name = "corpus") corpus("corpus"),
        @Json(name = "corrupted") corrupted("corrupted");
    }
}

