/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Rarities

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * What you can get from this mission as reward
 *
 * @param type 
 * @param item id of an item
 * @param mission id of a mission
 * @param location id of a location
 * @param rate Chance to get item on mission completion or rotation completion
 * @param rarity 
 * @param rotation 
 */


data class MissionDropData (

    @Json(name = "type")
    val type: MissionDropData.Type? = null,

    /* id of an item */
    @Json(name = "item")
    val item: kotlin.String? = null,

    /* id of a mission */
    @Json(name = "mission")
    val mission: kotlin.String? = null,

    /* id of a location */
    @Json(name = "location")
    val location: kotlin.String? = null,

    /* Chance to get item on mission completion or rotation completion */
    @Json(name = "rate")
    val rate: java.math.BigDecimal? = null,

    @Json(name = "rarity")
    val rarity: Rarities? = null,

    @Json(name = "rotation")
    val rotation: MissionDropData.Rotation? = null

) {

    /**
     * 
     *
     * Values: mission
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "mission") mission("mission");
    }
    /**
     * 
     *
     * Values: b,a,c
     */
    @JsonClass(generateAdapter = false)
    enum class Rotation(val value: kotlin.String) {
        @Json(name = "b") b("b"),
        @Json(name = "a") a("a"),
        @Json(name = "c") c("c");
    }
}

