/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param urlName 
 * @param itemName Name of the quirk
 * @param description Description of the quirk
 * @param group which group this element belongs to, is used to display specific groups on the frontend.
 */


data class NemesisQuirk (

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "url_name")
    val urlName: kotlin.String? = null,

    /* Name of the quirk */
    @Json(name = "item_name")
    val itemName: kotlin.String? = null,

    /* Description of the quirk */
    @Json(name = "description")
    val description: kotlin.String? = null,

    /* which group this element belongs to, is used to display specific groups on the frontend. */
    @Json(name = "group")
    val group: kotlin.String? = null

)

