/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Known npc
 *
 * @param id 
 * @param urlName 
 * @param icon 
 * @param thumb 
 * @param name Npc name
 */


data class Npc (

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "url_name")
    val urlName: kotlin.String? = null,

    @Json(name = "icon")
    val icon: kotlin.String? = null,

    @Json(name = "thumb")
    val thumb: kotlin.String? = null,

    /* Npc name */
    @Json(name = "name")
    val name: kotlin.String? = null

)

