/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Rarities

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * What you can get from this npc
 *
 * @param type 
 * @param item id of an item
 * @param npc id of an npc
 * @param rate Chance to get item on kill
 * @param rarity 
 */


data class NpcDropData (

    @Json(name = "type")
    val type: NpcDropData.Type? = null,

    /* id of an item */
    @Json(name = "item")
    val item: kotlin.String? = null,

    /* id of an npc */
    @Json(name = "npc")
    val npc: kotlin.String? = null,

    /* Chance to get item on kill */
    @Json(name = "rate")
    val rate: java.math.BigDecimal? = null,

    @Json(name = "rarity")
    val rarity: Rarities? = null

) {

    /**
     * 
     *
     * Values: npc
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "npc") npc("npc");
    }
}

