/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param item ObjectId of an item
 * @param orderType 
 * @param platinum 
 * @param quantity 
 * @param visible 
 * @param rank 
 * @param subtype Check item `subtypes` field for possible values
 */


data class ProfileOrdersPostRequest (

    /* ObjectId of an item */
    @Json(name = "item")
    val item: kotlin.String? = null,

    @Json(name = "order_type")
    val orderType: ProfileOrdersPostRequest.OrderType? = null,

    @Json(name = "platinum")
    val platinum: kotlin.Int? = null,

    @Json(name = "quantity")
    val quantity: kotlin.Int? = null,

    @Json(name = "visible")
    val visible: kotlin.Boolean? = null,

    @Json(name = "rank")
    val rank: kotlin.Int? = null,

    /* Check item `subtypes` field for possible values */
    @Json(name = "subtype")
    val subtype: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: sell,buy
     */
    @JsonClass(generateAdapter = false)
    enum class OrderType(val value: kotlin.String) {
        @Json(name = "sell") sell("sell"),
        @Json(name = "buy") buy("buy");
    }
}

