/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Rarities
import org.openapitools.client.models.RelicDropDataRates

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * What you can get from this relic
 *
 * @param type 
 * @param item id of an item
 * @param relic id of a relic
 * @param rates 
 * @param rarity 
 */


data class RelicDropData (

    @Json(name = "type")
    val type: RelicDropData.Type? = null,

    /* id of an item */
    @Json(name = "item")
    val item: kotlin.String? = null,

    /* id of a relic */
    @Json(name = "relic")
    val relic: kotlin.String? = null,

    @Json(name = "rates")
    val rates: RelicDropDataRates? = null,

    @Json(name = "rarity")
    val rarity: Rarities? = null

) {

    /**
     * 
     *
     * Values: relic
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "relic") relic("relic");
    }
}

