/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param intact chance to get an item from intact relic
 * @param exceptional chance to get an item from exceptional relic
 * @param flawless chance to get an item from flawless relic
 * @param radiant chance to get an item from radiant relic
 */


data class RelicDropDataRates (

    /* chance to get an item from intact relic */
    @Json(name = "intact")
    val intact: java.math.BigDecimal? = null,

    /* chance to get an item from exceptional relic */
    @Json(name = "exceptional")
    val exceptional: java.math.BigDecimal? = null,

    /* chance to get an item from flawless relic */
    @Json(name = "flawless")
    val flawless: java.math.BigDecimal? = null,

    /* chance to get an item from radiant relic */
    @Json(name = "radiant")
    val radiant: java.math.BigDecimal? = null

)

