/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param positive 
 * @param `value` 
 * @param urlName 
 */


data class RivenAuctionAttributesInner (

    @Json(name = "positive")
    val positive: kotlin.Boolean? = null,

    @Json(name = "value")
    val `value`: kotlin.Int? = null,

    @Json(name = "url_name")
    val urlName: kotlin.String? = null

)

