/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.RivenAuctionAttributesInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type type of the item, in this case it's `riven`
 * @param attributes 
 * @param name Riven mod name
 * @param masteryLevel Mastery level requirennment for that mod.
 * @param reRolls 
 * @param weaponUrlName weapon name in url format.
 * @param polarity 
 * @param modRank 
 */


data class RivenAuction (

    /* type of the item, in this case it's `riven` */
    @Json(name = "type")
    val type: kotlin.String? = null,

    @Json(name = "attributes")
    val attributes: kotlin.collections.List<RivenAuctionAttributesInner>? = null,

    /* Riven mod name */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* Mastery level requirennment for that mod. */
    @Json(name = "mastery_level")
    val masteryLevel: kotlin.Int? = null,

    @Json(name = "re_rolls")
    val reRolls: kotlin.Int? = null,

    /* weapon name in url format. */
    @Json(name = "weapon_url_name")
    val weaponUrlName: kotlin.String? = null,

    @Json(name = "polarity")
    val polarity: RivenAuction.Polarity? = null,

    @Json(name = "mod_rank")
    val modRank: kotlin.Int? = null

) {

    /**
     * 
     *
     * Values: madurai,vazarin,naramon,zenurik
     */
    @JsonClass(generateAdapter = false)
    enum class Polarity(val value: kotlin.String) {
        @Json(name = "madurai") madurai("madurai"),
        @Json(name = "vazarin") vazarin("vazarin"),
        @Json(name = "naramon") naramon("naramon"),
        @Json(name = "zenurik") zenurik("zenurik");
    }
}

