/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param payload 
 */


data class SettingsNotificationsPushPost200Response (

    @Json(name = "payload")
    val payload: SettingsNotificationsPushPost200Response.Payload? = null

) {

    /**
     * 
     *
     * Values: ok
     */
    @JsonClass(generateAdapter = false)
    enum class Payload(val value: kotlin.String) {
        @Json(name = "ok") ok("ok");
    }
}

