/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.SettingsNotificationsPushPostRequestOneOfSubscriptionKeys

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param endpointeger 
 * @param propertyKeys 
 */


data class SettingsNotificationsPushPostRequestOneOfSubscription (

    @Json(name = "endpointeger")
    val endpointeger: kotlin.String,

    @Json(name = "keys")
    val propertyKeys: SettingsNotificationsPushPostRequestOneOfSubscriptionKeys

)

