/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param ingameName 
 * @param status 
 * @param region 
 * @param reputation 
 * @param avatar 
 * @param lastSeen 
 */


data class UserShort (

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "ingame_name")
    val ingameName: kotlin.String? = null,

    @Json(name = "status")
    val status: UserShort.Status? = null,

    @Json(name = "region")
    val region: kotlin.String? = null,

    @Json(name = "reputation")
    val reputation: kotlin.Int? = null,

    @Json(name = "avatar")
    val avatar: kotlin.String? = null,

    @Json(name = "last_seen")
    val lastSeen: java.time.OffsetDateTime? = null

) {

    /**
     * 
     *
     * Values: ingame,online,offline
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "ingame") ingame("ingame"),
        @Json(name = "online") online("online"),
        @Json(name = "offline") offline("offline");
    }
}

